name: ringo_workspace
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - apps/ringo
  - features/onboarding
  - features/ring_setup
  - packages/app_info
  - packages/bloc
  - packages/design_lint
  - packages/errors
  - packages/i18n
  - packages/launcher
  - packages/logger
  - packages/observer
  - packages/remote_config
  - packages/result
  - packages/ring_protocol
  - packages/ring_transport
  - packages/storage_tostore
  - packages/ui_kit
  - packages/utils

dev_dependencies:
  melos: ^7.4.0

melos:
  command:
    bootstrap:
      usePubspecOverrides: true
