name: sleep
description: Sleep feature for the Ringo application.
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  go_router: ^16.3.0
  provider: ^6.1.5+1
  ring_sleep_sync:
    path: ../../packages/ring_sleep_sync
  ring_transport:
    path: ../../packages/ring_transport
  sleep_analysis:
    path: ../../packages/sleep_analysis
  storage_tostore:
    path: ../../packages/storage_tostore
  ui_kit:
    path: ../../packages/ui_kit

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
