name: remote_config
description: Remote configuration service, repository and ConfigCubit for Ringo
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.5"

dependencies:
  errors:
    path: ../errors
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  result:
    path: ../result
  talker: ^5.1.9
  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
