name: onboarding
description: Ringo onboarding feature.
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  permission_handler: ^13.0.1
  ring_protocol:
    path: ../../packages/ring_protocol
  ring_transport:
    path: ../../packages/ring_transport
  ui_kit:
    path: ../../packages/ui_kit

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
