name: ringo
description: Ringo Flutter application
publish_to: none
resolution: workspace

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  app_shell:
    path: ../../features/app_shell
  flutter:
    sdk: flutter
  onboarding:
    path: ../../features/onboarding
  ring_sleep_sync:
    path: ../../packages/ring_sleep_sync
  ring_transport:
    path: ../../packages/ring_transport
  sleep_analysis:
    path: ../../packages/sleep_analysis
  ui_kit:
    path: ../../packages/ui_kit

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
