name: bloc_exports
description: Re-exports flutter_bloc, bloc, provider, pine and freezed_annotation at consistent versions
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  meta: ^1.17.0
  pine: ^1.0.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
