name: utils
description: Shared utilities, extensions, constants and persistence for Ringo
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.5"

dependencies:
  flutter:
    sdk: flutter
  pine: ^1.0.4
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
