name: app_info
description: App version and platform info service, repository and VersionCheckerBloc for Ringo
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.5"

dependencies:
  bloc_exports:
    path: ../bloc
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  package_info_plus: ^9.0.0
  result:
    path: ../result

dev_dependencies:
  flutter_test:
    sdk: flutter
